on:
  push:
    branches:
      - release-please--**
      - renovate/**
name: Build dist
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci

      - run: npm run build

      - name: Commit dist
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          if echo "$GITHUB_REF_NAME" | grep -q -- '--components--'; then
            COMPONENT=$(echo "$GITHUB_REF_NAME" | sed 's/.*--components--//')
            git add packages/$COMPONENT/dist
          else
            git add packages/*/dist
          fi
          git diff --cached --quiet || (git commit -m "chore: build dist [skip ci]" && git push origin)
